const CAD3 = [
 
    
    {
       id: 121,
       text: "Which of the following statements is true about Guided Application Creator?",
       options: [
         "The global scope option is turned on by default",
         "Default access controls are automatically created",
         "The welcome screen appears every time a new application is created",
         "A scoped application user role is automatically created"
       ],
       correctAnswers: ["Default access controls are automatically created"],
       multipleChoice: false
    },
    {
       id: 122,
       text: "What are the ways to designate data tables when using Guided Application Creator (GAC)? (Choose three.)",
       options: [
         "Upload an existing PDF",
         "Create a new table on the platform",
         "Use a freeform database",
         "Upload an existing spreadsheet",
         "Use an existing table on the platform",
         "Upload an existing word processing document"
       ],
       correctAnswers: ["Create a new table on the platform", "Upload an existing spreadsheet", "Use an existing table on the platform"],
       multipleChoice: true
    },
    {
       id: 123,
       text: "Which of the following is NOT a caller access field option?",
       options: [
         "Caller Tracking",
         "Caller Restriction",
         "None",
         "Caller Permission"
       ],
       correctAnswers: ["Caller Permission"],
       multipleChoice: false
    },
    {
       id: 124,
       text: "Which method is used to retrieve Application Property values in a script?",
       options: [
         "gs.getProperty()",
         "g_form.getAppProperty()",
         "g_form.getProperty()",
         "gs.getAppProperty()"
       ],
       correctAnswers: ["gs.getProperty()"],
       multipleChoice: false
    },
    {
       id: 125,
       text: "What Module Link type is used to access an Application Properties page?",
       options: [
         "Single Record",
         "HTML (from Arguments)",
         "URL (from Arguments)",
         "Script (from Arguments)"
       ],
       correctAnswers: ["URL (from Arguments)"],
       multipleChoice: false
    },
    {
       id: 126,
       text: "Identify the way(s) an application can respond to an Event generated by the gs.eventQueue() method.",
       options: [
         "Script Action",
         "Scheduled Script Execution (Scheduled Job)",
         "UI Policy",
         "Email Notification"
       ],
       correctAnswers: [ "Email Notification",  "Script Action"],
       multipleChoice: true
    },
    {
       id: 127,
       text: "When troubleshooting and debugging notifications, where do you navigate to see if an email was sent in response to an event?",
       options: [
         "System Logs > Events",
         "System Logs > Emails",
         "System Logs > Push Notifications",
         "System Logs > ICE Logs"
       ],
       correctAnswers: ["System Logs > Emails"],
       multipleChoice: false
    },
    {
       id: 128,
       text: "What are three ServiceNow table creation methods? (Choose three.)",
       options: [
         "Using legacy Workflows",
         "Upload and turn a spreadsheet into a custom table",
         "Using Flow Designer",
         "Use the Now Experience Table Creator",
         "Extend a table",
         "Create a custom table"
       ],
       correctAnswers: ["Upload and turn a spreadsheet into a custom table", "Extend a table", "Create a custom table"],
       multipleChoice: true
    },
    {
       id: 129,
       text: "When selecting a data type for a field that will be displayed on a form, which of the following statements is NOT correct?",
       options: [
         "Use the String data type for a free-form text field",
         "Use the Phone Number data type to automate phone number data validation",
         "Use the Choice data type to limit options in a field",
         "Use the Date data type to enter the date and time of day"
       ],
       correctAnswers: ["Use the Date data type to enter the date and time of day"],
       multipleChoice: false
    },
    {
       id: 130,
       text: "Which one of the following is NOT part of the Form Designer?",
       options: [
         "Page header",
         "Schema map",
         "Field navigator",
         "Form layout"
       ],
       correctAnswers: ["Schema map"],
       multipleChoice: false
    },
    {
       id: 131,
       text: "Which class is NOT part of the Client side scoped APIs?",
       options: [
         "GlideDialogWindow",
         "GlideAjax",
         "GlideRecord",
         "GlideForm"
       ],
       correctAnswers: ["GlideRecord"],
       multipleChoice: false
    },
    {
       id: 132,
       text: "When designing and creating a form what do you create to organize fields on a form?",
       options: [
         "Buttons",
         "Tabs",
         "Sections",
         "Related lists"
       ],
       correctAnswers: ["Sections"],
       multipleChoice: false
    },
    {
       id: 133,
       text: "Which one of the following is a good practice for adding instructions to a form?",
       options: [
         "Related links to wiki pages",
         "A Context Menu UI Action",
         "Annotations",
         "A populated read-only field"
       ],
       correctAnswers: ["Annotations"],
       multipleChoice: false
    },
    {
       id: 134,
       text: "Which of the following GlideRecord methods run a query against a database table? (Choose three.)",
       options: [
         "_get()",
         "runQuery()",
         "query()",
         "_query()",
         "get()"
       ],
       correctAnswers: ["query()", "_query()", "get()"],
       multipleChoice: true
    },
    {
       id: 135,
       text: "What is the GlideForm Client-side scripting object?",
       options: [
         "sn.form",
         "g_form",
         "gs.form",
         "gs_form"
       ],
       correctAnswers: ["g_form"],
       multipleChoice: false
    },
    {
       id: 136,
       text: "In a Business Rule, which one of the following returns the sys_id of the currently logged in user?",
       options: [
         "g_form.getUserID()",
         "gs.getUserSysID()",
         "gs.getUserID()",
         "g_form.getUserSysID()"
       ],
       correctAnswers: ["gs.getUserID()"],
       multipleChoice: false
    },
    {
       id: 137,
       text: "Access Control debug information identifies whether each element of an Access Control granted or denied access. The elements appear in the debug information in the order of evaluation. In which order are the elements of an Access Control evaluated?",
       options: [
         "Conditions, Roles, Script",
         "Conditions, Script, Roles",
         "Roles, Conditions, Script",
         "Script, Conditions, Roles"
       ],
       correctAnswers: ["Roles, Conditions, Script"],
       multipleChoice: false
    },
    {
       id: 138,
       text: "When debugging Email Notifications, what must you check on a user record? (Choose three.)",
       options: [
         "Active must be true",
         "The First name and Last name fields must have values",
         "The value in the Notification field must be set to enabled",
         "The user must not be locked out",
         "The Email field must have a value"
       ],
       correctAnswers: ["Active must be true", "The value in the Notification field must be set to enabled", "The Email field must have a value"],
       multipleChoice: true
    },
    {
       id: 139,
       text: "What are web services?",
       options: [
         "Methods used to create and maintain UI Pages",
         "Methods used to allow applications to connect to other software applications over a network",
         "Methods used to discover a wide variety of systems and applications",
         "They provide a customer-facing view of available service and product offerings provided by departments within the organization"
       ],
       correctAnswers: ["Methods used to allow applications to connect to other software applications over a network"],
       multipleChoice: false
    },
    {
       id: 140,
       text: "What do you need to do before you can use an Application-based trigger in your flow?",
       options: [
         "Activate application trigger spoke",
         "Activate trigger security rules",
         "Activate application spoke, and plug-ins as needed",
         "Assign Application trigger role [sn_app_trigger_write] to SME",
         "Activate application plugins only"
       ],
       correctAnswers: ["Activate application spoke, and plug-ins as needed"],
       multipleChoice: false
    },
    {
       id: 141,
       text: "You are developing the MyApp application that has a table, Table A. When the MyApp application is installed on an instance, you want Table A's records to be installed as part of the application. Table A's records will be installed when:",
       options: [
         "Table A is active and extends the Task table",
         "Table A's records are added to the application record using the Create Application Files context menu item",
         "Table A has an automatic number counter for new records",
         "Table A is not included in the System Clone > Exclude Tables list"
       ],
       correctAnswers: ["Table A's records are added to the application record using the Create Application Files context menu item"],
       multipleChoice: false
    },
    {
       id: 142,
       text: "How can an application link to a repository behind a firewall?",
       options: [
         "This option is not supported.",
         "Link an application to source control through a MID Server.",
         "Link an application to source control through an access token.",
         "Link an application to source control with multi-factor authentication."
       ],
       correctAnswers: ["Link an application to source control through a MID Server."],
       multipleChoice: false
    },
    {
       id: 143,
       text: "What is the ServiceNow store?",
       options: [
         "Downloadable content ServiceNow script archive",
         "Alternate name for the ServiceNow Developer Share site",
         "The source for ServiceNow Community created developer content",
         "Marketplace for free and paid certified ServiceNow applications and integrations"
       ],
       correctAnswers: ["Marketplace for free and paid certified ServiceNow applications and integrations"],
       multipleChoice: false
    },
    {
       id: 144,
       text: "Tables that extend a table do what?",
       options: [
         "Automatically update the application scope",
         "Do not inherit the parent’s fields",
         "Sometimes inherit the parent’s fields",
         "Inherit the parent’s fields"
       ],
       correctAnswers: ["Inherit the parent’s fields"],
       multipleChoice: false
    },
    {
       id: 145,
       text: "When creating an application through the Guided Application Creator, which of the following is NOT an option for creating a table?",
       options: [
         "Create table from template",
         "Create table from scratch",
         "Extend a table",
         "Upload spreadsheet"
       ],
       correctAnswers: ["Create table from template"],
       multipleChoice: false
    },
    {
       id: 146,
       text: "Server-side scripts manage what?",
       options: [
         "Database and backend",
         "Playbook access",
         "User access",
         "Forms and Fields"
       ],
       correctAnswers: ["Database and backend"],
       multipleChoice: false
    },
    {
       id: 147,
       text: "What intuitive development interface guides users through the initial application development process?",
       options: [
         "Guided Tour Designer",
         "Guided Application Creator",
         "ServiceNow Studio",
         "Flow Designer"
       ],
       correctAnswers: ["Guided Application Creator"],
       multipleChoice: false
    },
    {
       id: 148,
       text: "What are some benefits of developing private, scoped applications? (Choose two.)",
       options: [
         "To avoid using a code repository like GitHub or GitLab",
         "To reduce risk at code collisions",
         "To enable installation and uninstallation of an application",
         "To replicate ServiceNow functions a private scope"
       ],
       correctAnswers: ["To reduce risk at code collisions", "To enable installation and uninstallation of an application"],
       multipleChoice: true
    },
    {
       id: 149,
       text: "What plugin enables the Guided Application Creator?",
       options: [
         "com.glide.sn-guided-app-creator",
         "com.glide.service_creator",
         "com.glide.snc.apps_creator",
         "com.snc.apps_creator_template"
       ],
       correctAnswers: ["com.glide.sn-guided-app-creator"],
       multipleChoice: false
    },
    {
       id: 150,
       text: "Which of the following can be an external data source for a ServiceNow application?",
       options: [
         "Microsoft Excel File",
         "Data provided by a public web service using SOAP or REST",
         "CSV file",
         "All of the above"
       ],
       correctAnswers: ["All of the above"],
       multipleChoice: false
    },
    {
       id: 151,
       text: "Which one of the following is true for the Application Picker and Application Scope?",
       options: [
         "Global is a reserved application which does not appear in the Application Picker",
         "Selecting an application from the Application Picker does not set the Application Scope",
         "Selecting an application from the Application Picker sets the Application Scope",
         "Selecting Global in the Application Picker sets the Application Scope to Incident"
       ],
       correctAnswers: ["Selecting an application from the Application Picker sets the Application Scope"],
       multipleChoice: false
    },
    {
       id: 152,
       text: "Which of the following is an available feature in Studio? (Choose two.)",
       options: [
         "Push to update set",
         "Merge branches",
         "Search code",
         "Push to external source control"
       ],
       correctAnswers: ["Search code", "Push to external source control"],
       multipleChoice: true
    },
    {
       id: 153,
       text: "The Task table is an example of which of the following? (Choose two.)",
       options: [
         "Parent class",
         "Legacy class",
         "Child class",
         "Base class"
       ],
       correctAnswers: ["Parent class", "Base class"],
       multipleChoice: true
    },
    {
       id: 154,
       text: "Which of the following is true about deleting fields from a table?",
       options: [
         "Table records are deleted when a field is deleted",
         "User-defined non-inherited fields can be deleted",
         "Any field on a table can be deleted",
         "Inherited fields can be deleted"
       ],
       correctAnswers: ["User-defined non-inherited fields can be deleted"],
       multipleChoice: false
    },
    
      {
        id: 155,
        text: "Why would you build a custom app? (Choose two.)",
        options: [
          "To avoid using a code repository like GitHub or GitLab",
          "To replace ServiceNow base tables",
          "To fulfill a specific use case on internal processes",
          "To create a custom integration for a 3rd party system"
        ],
        correctAnswers: ["To fulfill a specific use case on internal processes", "To create a custom integration for a 3rd party system"],
        multipleChoice: true
      }
    ]; 
  
  
    export default CAD3;
  