const CAD3 = [
  {
    "id": 129,
    "text": "Using Custom UI test step in Automated Test Framework, which of the following is NOT a testable page component?",
    "options": [
      "A. Buttons",
      "B. UI controls",
      "C. UI pages",
      "D. Form field values"
    ],
    "correctAnswers": [
      "D. Form field values"
    ],
    "multipleChoice": false
  },
  {
    "id": 130,
    "text": "Why create Applications in ServiceNow? a) To replace outdated, inadequate, custom business applications and processes b) To extend service delivery and management to all enterprise departments c) To allow users full access to all ServiceNow tables, records, and fields d) To extend the value of ServiceNow",
    "options": [
      "A. a, b, and d",
      "B. a, b, c, and d",
      "C. a, b, and c",
      "D. b, c, and d"
    ],
    "correctAnswers": [
      "A. a, b, and d"
    ],
    "multipleChoice": false
  },
  {
    "id": 131,
    "text": "Flow Designer supports variable data types to store record data and complex data. Which of the following are supported variable data types? (Choose three.)",
    "options": [
      "A. Choice data type",
      "B. Array.Reference data type",
      "C. Integer data type",
      "D. Freedom data type",
      "E. Array.Boolean data type",
      "F. Label data type"
    ],
    "correctAnswers": [
      "A. Choice data type",
      "C. Integer data type",
      "E. Array.Boolean data type"
    ],
    "multipleChoice": true
  },
  {
    "id": 132,
    "text": "Which of the following statements is true about Guided Application Creator?",
    "options": [
      "A. The global scope option is turned on by default",
      "B. Default access controls are automatically created",
      "C. The welcome screen appears every time a new application is created",
      "D. A scoped application user role is automatically created"
    ],
    "correctAnswers": [
      "B. Default access controls are automatically created"
    ],
    "multipleChoice": false
  },
  {
    "id": 133,
    "text": "What are the ways to designate data tables when using Guided Application Creator (GAC)? (Choose three.)",
    "options": [
      "A. Upload an existing PDF",
      "B. Create a new table on the platform",
      "C. Use a freeform database",
      "D. Upload an existing spreadsheet",
      "E. Use an existing table on the platform",
      "F. Upload an existing word processing document"
    ],
    "correctAnswers": [
      "B. Create a new table on the platform",
      "D. Upload an existing spreadsheet",
      "E. Use an existing table on the platform"
    ],
    "multipleChoice": true
  },
  {
    "id": 134,
    "text": "What is the Event Registry?",
    "options": [
      "A. A Workflow which is launched every time an Event is generated; used to debug Events",
      "B. The Event Log which lists all Events that have been generated",
      "C. The method used in server side scripts to generate Events and pass parameters",
      "D. A table containing a record for every Event known to the ServiceNow system which allows ServiceNow to react when Events are generated"
    ],
    "correctAnswers": [
      "D. A table containing a record for every Event known to the ServiceNow system which allows ServiceNow to react when Events are generated"
    ],
    "multipleChoice": false
  },
  {
    "id": 135,
    "text": "Identify the ways an application can respond to an Event generated by the gs.eventQueue() method: (Choose two.)",
    "options": [
      "A. Client Script",
      "B. Email Notification",
      "C. Scheduled Script Execution (Scheduled Job)",
      "D. Script Action",
      "E. UI Policy"
    ],
    "correctAnswers": [
      "B. Email Notification",
      "D. Script Action"
    ],
    "multipleChoice": true
  },
  {
    "id": 136,
    "text": "Is it possible to change an application’s scope?",
    "options": [
      "A. No, it’s not possible",
      "B. Yes, it’s possible",
      "C. Yes, but only from global scope to private scope",
      "D. Yes, but only from private scope to global scope"
    ],
    "correctAnswers": [
      "A. No, it’s not possible"
    ],
    "multipleChoice": false
  },
  {
    "id": 137,
    "text": "Which of the following is true about g_scratchpad? (Choose two.)",
    "options": [
      "A. Used to push information from the server to the client",
      "B. Does not exist on the mobile platform",
      "C. Has constructors and methods",
      "D. Has default properties passed by client-side scripts"
    ],
    "correctAnswers": [
      "A. Used to push information from the server to the client",
      "B. Does not exist on the mobile platform"
    ],
    "multipleChoice": true
  },
  {
    "id": 138,
    "text": "Client-side scripts manage what?",
    "options": [
      "A. User access",
      "B. Database and backend",
      "C. Playbook access",
      "D. Forms and Form Fields"
    ],
    "correctAnswers": [
      "D. Forms and Form Fields"
    ],
    "multipleChoice": false
  },
  {
    "id": 139,
    "text": "When debugging Email Notifications, what must you check on a user record? (Choose two.)",
    "options": [
      "A. Active must be true.",
      "B. The Email field must have a valid value.",
      "C. The user must not be locked out.",
      "D. The First name and Last name fields must have values.",
      "E. Delegation must be enabled."
    ],
    "correctAnswers": [
      "A. Active must be true.",
      "B. The Email field must have a valid value."
    ],
    "multipleChoice": true
  },
  {
    "id": 140,
    "text": "When crafting a scoped application that contains flow actions, what is the application called?",
    "options": [
      "A. Action",
      "B. Spoke",
      "C. Bundle",
      "D. Flow"
    ],
    "correctAnswers": [
      "B. Spoke"
    ],
    "multipleChoice": false
  },
  {
    "id": 141,
    "text": "Which are reasons an application could be developed on the ServiceNow platform? (Choose three.)",
    "options": [
      "A. It needs workflow to manage processes.",
      "B. It requires reporting capabilities.",
      "C. It uses forms extensively to interact with data.",
      "D. It requires low-level programming libraries.",
      "E. It uses multimedia features."
    ],
    "correctAnswers": [
      "A. It needs workflow to manage processes.",
      "B. It requires reporting capabilities.",
      "C. It uses forms extensively to interact with data."
    ],
    "multipleChoice": true
  },
  {
    "id": 142,
    "text": "Once an application is ready to share, which of the following methods of publishing are supported by ServiceNow? (Choose three.)",
    "options": [
      "A. Publish to an application repository",
      "B. Publish to a local drive",
      "C. Publish to the ServiceNow Store",
      "D. Publish to an Update Set",
      "E. Publish to a spreadsheet",
      "F. Publish to a local USB device"
    ],
    "correctAnswers": [
      "A. Publish to an application repository",
      "C. Publish to the ServiceNow Store",
      "D. Publish to an Update Set"
    ],
    "multipleChoice": true
  },
  {
    "id": 143,
    "text": "What is required to link a ServiceNow application to a Git repository? (Choose three.)",
    "options": [
      "A. URI",
      "B. ACL",
      "C. Application name",
      "D. Password",
      "E. User name",
      "F. URL"
    ],
    "correctAnswers": [
      "D. Password",
      "E. User name",
      "F. URL"
    ],
    "multipleChoice": true
  },
  {
    "id": 144,
    "text": "What is the Endpoint when configuring a REST Message?",
    "options": [
      "A. The URI of the WebServer",
      "B. The command to the REST script to stop execution",
      "C. The URI of the data to be accessed, queried, or modified",
      "D. The provider response indicates there is no data to send back"
    ],
    "correctAnswers": [
      "C. The URI of the data to be accessed, queried, or modified"
    ],
    "multipleChoice": false
  },
  {
    "id": 145,
    "text": "Which client-side scripts apply to Record Producers? (Choose two.)",
    "options": [
      "A. Fix Scripts",
      "B. Catalog Client Scripts",
      "C. UI Scripts",
      "D. Catalog UI Policies",
      "E. Record Producer Policies"
    ],
    "correctAnswers": [
      "B. Catalog Client Scripts",
      "D. Catalog UI Policies"
    ],
    "multipleChoice": true
  },
  {
    "id": 146,
    "text": "Which business requirements and process(es) should be documented as part of the application development plan? (Choose four.)",
    "options": [
      "A. Available licenses",
      "B. Business problem",
      "C. Process steps",
      "D. Users/stakeholders",
      "E. Database capacity",
      "F. Project schedule",
      "G. Data input/output"
    ],
    "correctAnswers": [
      "B. Business problem",
      "C. Process steps",
      "D. Users/stakeholders",
      "G. Data input/output"
    ],
    "multipleChoice": true
  },
  {
    "id": 147,
    "text": "Which of the following is true for a Script Include with Client Callable selected?",
    "options": [
      "A. It can be called from a Business Rule",
      "B. It can be called from a Client Script",
      "C. It can only be called from another Script Include",
      "D. It can only be called from a Workflow"
    ],
    "correctAnswers": [
      "B. It can be called from a Client Script"
    ],
    "multipleChoice": false
  },
  {
    "id": 148,
    "text": "Which of the following is NOT a type of Client Script?",
    "options": [
      "A. onLoad",
      "B. onChange",
      "C. onSubmit",
      "D. onUpdate"
    ],
    "correctAnswers": [
      "D. onUpdate"
    ],
    "multipleChoice": false
  },
  {
    "id": 149,
    "text": "What functionality does a UI Policy provide without scripting?",
    "options": [
      "A. Set field values and write to system logs",
      "B. Set field values and make fields mandatory, visible, or read-only",
      "C. Query the database and update records",
      "D. Create or delete records"
    ],
    "correctAnswers": [
      "B. Set field values and make fields mandatory, visible, or read-only"
    ],
    "multipleChoice": false
  },
  {
    "id": 150,
    "text": "Which object is used to access information about the currently logged in user on the client side?",
    "options": [
      "A. GlideSystem (gs)",
      "B. GlideRecord",
      "C. GlideUser (g_user)",
      "D. GlideForm (g_form)"
    ],
    "correctAnswers": [
      "C. GlideUser (g_user)"
    ],
    "multipleChoice": false
  },
  {
    "id": 151,
    "text": "Which of the following statements is true about Business Rules?",
    "options": [
      "A. Business Rules only run before a database action",
      "B. Business Rules run on the client side",
      "C. Business Rules can run before or after a database action",
      "D. Business Rules only run after a database action"
    ],
    "correctAnswers": [
      "C. Business Rules can run before or after a database action"
    ],
    "multipleChoice": false
  },
  {
    "id": 152,
    "text": "Which of the following is NOT a valid GlideRecord operation?",
    "options": [
      "A. insert()",
      "B. update()",
      "C. deleteRecord()",
      "D. modify()"
    ],
    "correctAnswers": [
      "D. modify()"
    ],
    "multipleChoice": false
  },
  {
    "id": 153,
    "text": "Which one of the following is true about Reference fields?",
    "options": [
      "A. They store the display value of the referenced record",
      "B. They store the sys_id of the referenced record",
      "C. They can reference only the User table",
      "D. They cannot be indexed"
    ],
    "correctAnswers": [
      "B. They store the sys_id of the referenced record"
    ],
    "multipleChoice": false
  },
  {
    "id": 154,
    "text": "Which of the following is a use case for a Scheduled Script Execution?",
    "options": [
      "A. Validate form input when a record is saved",
      "B. Run a script at a specified time or interval",
      "C. Modify field behavior on a form",
      "D. Respond immediately to a database insert"
    ],
    "correctAnswers": [
      "B. Run a script at a specified time or interval"
    ],
    "multipleChoice": false
  },
  {
    "id": 155,
    "text": "Which of the following scripts run on the server? (Choose two.)",
    "options": [
      "A. Business Rules",
      "B. Client Scripts",
      "C. Script Includes",
      "D. UI Policies"
    ],
    "correctAnswers": [
      "A. Business Rules",
      "C. Script Includes"
    ],
    "multipleChoice": true
  },
  {
    "id": 156,
    "text": "Which one of the following is true about deleting records from a table?",
    "options": [
      "A. Deleting a record deletes the table",
      "B. Deleted records cannot be recovered",
      "C. Records can be deleted if the user has the correct permissions",
      "D. Records are only marked as inactive when deleted"
    ],
    "correctAnswers": [
      "C. Records can be deleted if the user has the correct permissions"
    ],
    "multipleChoice": false
  },
  {
    "id": 157,
    "text": "Which of the following objects can be used in a Script Include?",
    "options": [
      "A. current",
      "B. g_form",
      "C. GlideRecord",
      "D. producer"
    ],
    "correctAnswers": [
      "C. GlideRecord"
    ],
    "multipleChoice": false
  },
  {
    "id": 158,
    "text": "Which one of the following is true about UI Actions?",
    "options": [
      "A. UI Actions can only be client-side",
      "B. UI Actions can only be server-side",
      "C. UI Actions can be client-side, server-side, or both",
      "D. UI Actions cannot run scripts"
    ],
    "correctAnswers": [
      "C. UI Actions can be client-side, server-side, or both"
    ],
    "multipleChoice": false
  },
  {
    "id": 159,
    "text": "Which of the following is NOT a type of UI Action?",
    "options": [
      "A. Form button",
      "B. Form link",
      "C. List banner button",
      "D. List choice"
    ],
    "correctAnswers": [
      "D. List choice"
    ],
    "multipleChoice": false
  },
  {
    "id": 160,
    "text": "Which of the following methods can be used to add an informational message to a form on the client side?",
    "options": [
      "A. gs.addInfoMessage()",
      "B. g_form.addInfoMessage()",
      "C. g_user.addInfoMessage()",
      "D. GlideSystem.addInfoMessage()"
    ],
    "correctAnswers": [
      "B. g_form.addInfoMessage()"
    ],
    "multipleChoice": false
  },
  {
    "id": 161,
    "text": "Which of the following statements is true about Access Controls?",
    "options": [
      "A. Access Controls only apply to tables",
      "B. Access Controls apply only to fields",
      "C. Access Controls apply to both tables and fields",
      "D. Access Controls do not apply to scoped applications"
    ],
    "correctAnswers": [
      "C. Access Controls apply to both tables and fields"
    ],
    "multipleChoice": false
  },
  {
    "id": 162,
    "text": "Which of the following is NOT evaluated when determining access using an Access Control?",
    "options": [
      "A. Roles",
      "B. Conditions",
      "C. Scripts",
      "D. UI Policies"
    ],
    "correctAnswers": [
      "D. UI Policies"
    ],
    "multipleChoice": false
  },
  {
    "id": 163,
    "text": "Which of the following server-side APIs is available in scoped applications?",
    "options": [
      "A. gs.log()",
      "B. gs.info()",
      "C. gs.print()",
      "D. gs.debuglog()"
    ],
    "correctAnswers": [
      "B. gs.info()"
    ],
    "multipleChoice": false
  },
  {
    "id": 164,
    "text": "Which one of the following is true about email notifications?",
    "options": [
      "A. They can only be triggered manually",
      "B. They can be triggered by events or conditions",
      "C. They can only be sent to users",
      "D. They do not support HTML content"
    ],
    "correctAnswers": [
      "B. They can be triggered by events or conditions"
    ],
    "multipleChoice": false
  },
  {
    "id": 165,
    "text": "Which one of the following is NOT a valid trigger for Flow Designer?",
    "options": [
      "A. Record",
      "B. Schedule",
      "C. Application",
      "D. Email"
    ],
    "correctAnswers": [
      "D. Email"
    ],
    "multipleChoice": false
  },
  {
    "id": 166,
    "text": "Which one of the following is true about the application scope?",
    "options": [
      "A. Scope determines which users can access the application",
      "B. Scope determines where application artifacts are stored and how they are accessed",
      "C. Scope determines which UI Pages are visible",
      "D. Scope determines which roles are assigned automatically"
    ],
    "correctAnswers": [
      "B. Scope determines where application artifacts are stored and how they are accessed"
    ],
    "multipleChoice": false
  },
  {
    "id": 167,
    "text": "Which of the following is a benefit of using Flow Designer instead of legacy workflows?",
    "options": [
      "A. Flow Designer requires scripting for all actions",
      "B. Flow Designer is available only in Global scope",
      "C. Flow Designer provides a no-code / low-code experience",
      "D. Flow Designer replaces all Business Rules"
    ],
    "correctAnswers": [
      "C. Flow Designer provides a no-code / low-code experience"
    ],
    "multipleChoice": false
  },
  {
    "id": 168,
    "text": "Which of the following is NOT a supported trigger in Flow Designer?",
    "options": [
      "A. Record",
      "B. Schedule",
      "C. Email",
      "D. Application"
    ],
    "correctAnswers": [
      "C. Email"
    ],
    "multipleChoice": false
  },
  {
    "id": 169,
    "text": "What does the Application Picker allow a developer to do?",
    "options": [
      "A. Download applications from the ServiceNow Store",
      "B. Choose which application to edit and set the application scope",
      "C. Switch between instances",
      "D. Enable or disable plugins"
    ],
    "correctAnswers": [
      "B. Choose which application to edit and set the application scope"
    ],
    "multipleChoice": false
  },
  {
    "id": 170,
    "text": "Which one of the following is NOT a reason to extend a table?",
    "options": [
      "A. To reuse existing fields and functionality",
      "B. To automatically copy all records from the parent table",
      "C. To inherit business logic from the parent table",
      "D. To follow best practice data modeling"
    ],
    "correctAnswers": [
      "B. To automatically copy all records from the parent table"
    ],
    "multipleChoice": false
  },
  {
    "id": 171,
    "text": "Which of the following is true about deleting a table?",
    "options": [
      "A. Tables can be deleted only by ServiceNow Support",
      "B. Deleting a table deletes all records permanently",
      "C. Tables can be deleted and later restored from update sets",
      "D. Tables cannot be deleted once created"
    ],
    "correctAnswers": [
      "B. Deleting a table deletes all records permanently"
    ],
    "multipleChoice": false
  },
  {
    "id": 172,
    "text": "Which object is used to pass information from a server-side script to a client-side script?",
    "options": [
      "A. g_user",
      "B. g_form",
      "C. g_scratchpad",
      "D. current"
    ],
    "correctAnswers": [
      "C. g_scratchpad"
    ],
    "multipleChoice": false
  },
  {
    "id": 173,
    "text": "Which of the following is NOT a valid logging method in scoped applications?",
    "options": [
      "A. gs.info()",
      "B. gs.warn()",
      "C. gs.error()",
      "D. gs.log()"
    ],
    "correctAnswers": [
      "D. gs.log()"
    ],
    "multipleChoice": false
  },
  {
    "id": 174,
    "text": "Which of the following ServiceNow features supports test automation?",
    "options": [
      "A. Update Sets",
      "B. Automated Test Framework",
      "C. Flow Designer",
      "D. Service Catalog"
    ],
    "correctAnswers": [
      "B. Automated Test Framework"
    ],
    "multipleChoice": false
  },
  {
    "id": 175,
    "text": "Which of the following can be tested using Automated Test Framework? (Choose two.)",
    "options": [
      "A. Forms",
      "B. Lists",
      "C. Emails",
      "D. Scheduled Jobs"
    ],
    "correctAnswers": [
      "A. Forms",
      "B. Lists"
    ],
    "multipleChoice": true
  },
  {
    "id": 176,
    "text": "Which of the following is true about Application Properties?",
    "options": [
      "A. They are stored only in system properties",
      "B. They allow changes to application behavior without modifying code",
      "C. They can only be modified by developers",
      "D. They are used only for UI customization"
    ],
    "correctAnswers": [
      "B. They allow changes to application behavior without modifying code"
    ],
    "multipleChoice": false
  },
  {
    "id": 177,
    "text": "Which object is used to access form fields on the client side?",
    "options": [
      "A. g_user",
      "B. GlideRecord",
      "C. g_form",
      "D. GlideSystem"
    ],
    "correctAnswers": [
      "C. g_form"
    ],
    "multipleChoice": false
  },
  {
    "id": 178,
    "text": "Which of the following is NOT a type of Business Rule?",
    "options": [
      "A. Before",
      "B. After",
      "C. Async",
      "D. OnLoad"
    ],
    "correctAnswers": [
      "D. OnLoad"
    ],
    "multipleChoice": false
  },
  {
    "id": 179,
    "text": "Which one of the following is true about UI Policies?",
    "options": [
      "A. They only run on the server",
      "B. They require scripting",
      "C. They can control form field behavior without scripting",
      "D. They can only be applied to lists"
    ],
    "correctAnswers": [
      "C. They can control form field behavior without scripting"
    ],
    "multipleChoice": false
  },
  {
    "id": 180,
    "text": "Which of the following is a valid use case for a Script Include?",
    "options": [
      "A. Store reusable server-side logic",
      "B. Customize form layouts",
      "C. Control client-side field visibility",
      "D. Replace UI Policies"
    ],
    "correctAnswers": [
      "A. Store reusable server-side logic"
    ],
    "multipleChoice": false
  },
  {
    "id": 181,
    "text": "Which of the following statements is true about client-side scripting?",
    "options": [
      "A. Client-side scripts can access the database directly",
      "B. Client-side scripts manage form behavior and user interaction",
      "C. Client-side scripts replace server-side scripts",
      "D. Client-side scripts can run scheduled jobs"
    ],
    "correctAnswers": [
      "B. Client-side scripts manage form behavior and user interaction"
    ],
    "multipleChoice": false
  },
  {
    "id": 182,
    "text": "Which of the following is NOT a valid REST method?",
    "options": [
      "A. GET",
      "B. POST",
      "C. DELETE",
      "D. COPY"
    ],
    "correctAnswers": [
      "D. COPY"
    ],
    "multipleChoice": false
  },
  {
    "id": 183,
    "text": "Which object is used to interact with the database on the server side?",
    "options": [
      "A. g_form",
      "B. g_user",
      "C. GlideRecord",
      "D. g_scratchpad"
    ],
    "correctAnswers": [
      "C. GlideRecord"
    ],
    "multipleChoice": false
  },
  {
    "id": 184,
    "text": "Which of the following is true about Record Producers?",
    "options": [
      "A. They always create records in the sc_req_item table",
      "B. They provide a user-friendly way to create records",
      "C. They require scripting to function",
      "D. They cannot include images"
    ],
    "correctAnswers": [
      "B. They provide a user-friendly way to create records"
    ],
    "multipleChoice": false
  },
  {
    "id": 185,
    "text": "Which of the following can trigger an Email Notification?",
    "options": [
      "A. Business Rule only",
      "B. Event or record conditions",
      "C. Scheduled Job only",
      "D. Client Script only"
    ],
    "correctAnswers": [
      "B. Event or record conditions"
    ],
    "multipleChoice": false
  },
  {
    "id": 186,
    "text": "Which of the following is NOT part of ServiceNow Studio?",
    "options": [
      "A. Source control integration",
      "B. Application file management",
      "C. Schema Map editor",
      "D. Code search"
    ],
    "correctAnswers": [
      "C. Schema Map editor"
    ],
    "multipleChoice": false
  },
  {
    "id": 187,
    "text": "Which of the following statements is true about Update Sets?",
    "options": [
      "A. They capture data records automatically",
      "B. They track configuration changes",
      "C. They replace source control",
      "D. They can be shared only within one instance"
    ],
    "correctAnswers": [
      "B. They track configuration changes"
    ],
    "multipleChoice": false
  },
  {
    "id": 188,
    "text": "Which of the following is NOT a benefit of using scoped applications?",
    "options": [
      "A. Reduced risk of name collisions",
      "B. Easier application installation and removal",
      "C. Automatic access to all platform APIs",
      "D. Improved application security"
    ],
    "correctAnswers": [
      "C. Automatic access to all platform APIs"
    ],
    "multipleChoice": false
  },
  {
    "id": 189,
    "text": "Which object is used to get system properties in server-side scripts?",
    "options": [
      "A. g_form",
      "B. gs",
      "C. g_user",
      "D. GlideRecord"
    ],
    "correctAnswers": [
      "B. gs"
    ],
    "multipleChoice": false
  },
  {
    "id": 190,
    "text": "Which of the following is a valid reason to use Delegated Development?",
    "options": [
      "A. To allow non-admin users to develop applications in global scope",
      "B. To give developers unrestricted access to security records",
      "C. To limit what application files a developer can access",
      "D. To replace the need for application roles"
    ],
    "correctAnswers": [
      "C. To limit what application files a developer can access"
    ],
    "multipleChoice": false
  },
  {
    "id": 191,
    "text": "Which of the following is true about Application Menus?",
    "options": [
      "A. Each application can have only one menu",
      "B. Menus are used only by administrators",
      "C. An application can have multiple menus",
      "D. Menus cannot contain modules"
    ],
    "correctAnswers": [
      "C. An application can have multiple menus"
    ],
    "multipleChoice": false
  },
  {
    "id": 192,
    "text": "Which one of the following is NOT true for Modules?",
    "options": [
      "A. Modules open content pages",
      "B. Access to Modules is controlled with roles",
      "C. Every Module must be part of an Application Menu",
      "D. Every Module must be associated with a table"
    ],
    "correctAnswers": [
      "D. Every Module must be associated with a table"
    ],
    "multipleChoice": false
  }

    ]; 
  
  
    export default CAD3;
  
